### ISSUE TITLE
maintain gulp-order ?

### ISSUE THREAD

**Issue by rejas** [gulp-community/meta#1]
The maintainer of https://github.com/sirlantis/gulp-order would be willing to transfer it to this community, see https://github.com/sirlantis/gulp-order/pull/30#issuecomment-389954494

**Comment by rejas** [comment]
@demurgos are you still here?

**Comment by rejas** [comment]
@demurgos could you please state if you are willing to take over gulp-order or let somebofdy help you here?

**Comment by demurgos** [comment]
Hi,
Sorry for the long delay. Since it's the first issue to integrate a lib, I wanted to first write a PR detailing the transition process before coming back here. 
I moved to a new city and started a new job in the last weeks so I did not have enough time to get around writing this PR. Thanks for the reminders about the issue: I shouldn't have left in the dark despite this.
Beside detailing how to transfer repos, this also highlights the need to have a way to onboard other people in managing this org: it should not depend on a single person. At the moment there are 5 other persons in the org, but they also have other things to deal with. This is not sustainable at the moment.

Regarding the issue itself, I l looked into `gulp-order` and I agree: it would benefit from moving to this org. Regardless of the exact requirements we define, this package is popular (Github stars, downloads) and has tests (even if it would benefit from CI).

Here is what I propose you:
- Move the repo from `sirlantis/gulp-order` to `gulp-community/gulp-order`
- Grant write access to `gulp-community/gulp-order` to both @sirlantis and you (@rejas)

Regarding the `npm` package, we don't have a solution at the moment. You can ask @sirlantis to add you and/or me as a contributor. There's no "bot" account for gulp at the moment but I think that we'll need to setup something like this.

**Comment by mrcljx** [comment]
Thanks for getting this going, @rejas @demurgos.

I'd transfer the project to `gulp-community` this weekend unless you have objections.

**Comment by demurgos** [comment]
Hi, thanks for coming back to this. We still need to figure out the correct workflows for migrations.
I believe that you need to add me as a collaborator with access to the settings of https://github.com/sirlantis/gulp-order. (I am not very familiar how Github's transfers work)

**Comment by rejas** [comment]
There is an option in the red-zone-section of a repos settings to transfer ownership, which should be used. As for publishing new releases later there needs to be a transfer in the npm  ownership too.

**Comment by demurgos** [comment]
I do not have access to the settings page. Could you check if it's possible to give me access to those?

And write down how to do it? Somewhere in "collaborators" I believe?

**Comment by rejas** [comment]
@sirlantis has to do it of course. I dont have access to the page either.

**Comment by rejas** [comment]
Looking through my old issues I came across this. Do you still want to transfer your repo over to @demurgos meta repo, @sirlantis ?

**Comment by phated** [comment]
@rejas sure! I'm not sure if they are still active, but you can always transfer the repo and npm to me and I'll make sure it gets added here

**Comment by rejas** [comment]
@sirlantis seems to be online in github from time to time, so maybe he reads this and takes the steps you mention.

**Comment by rejas** [comment]
pinging @sirlantis in the hope that it gets transferred after all these years ;-)

**Comment by mrcljx** [comment]
![CleanShot 2022-12-29 at 12 17 45](https://user-images.githubusercontent.com/56807/209943794-9ccd6b42-ee03-4b64-87fc-7766d5221296.png)

**Comment by rejas** [comment]
thx @mrcljx but maybe @phated is the better target these days

**Comment by phated** [comment]
Please remember that you have to add me (https://www.npmjs.com/~phated) as an npm owner otherwise having the repo isn't valuable!

**Comment by mrcljx** [comment]
All done.

**Comment by phated** [comment]
Thanks! This looks good to go so I'll close this out.
